// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReclutamientoNovaJrMTG.Models
{
    public partial class Productos
    {
        public string ProductoId { get; set; }
        public bool HabilitarPrecio1 { get; set; }
        public string Precio1 { get; set; }
        public string Sucursales { get; set; }
        public byte[] CreadoPor { get; set; }
        public DateTime FechaAlta { get; set; }
        public string ModificadoPor { get; set; }
        public DateTime FechaModificacion { get; set; }
    }
}