// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReclutamientoNovaJrMTG.Models
{
    public partial class Sucursales
    {
        public string SucursalId { get; set; }
        public string NombreComercial { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string SucursalMatriz { get; set; }
        public string CreadoPor { get; set; }
        public DateTime FechaAlta { get; set; }
        public DateTime FechaModificacion { get; set; }
    }
}